[workspace]
resolver = "2"

members = [
    "sudo",
    "sudo_events",
    "win32resources",
    "sudo_ap_broker",
]

# This list of dependencies allows us to specify version numbers for dependency in a single place.
# The dependencies in this list are _not_ automatically added to crates (Cargo.toml files).
# Each individual Cargo.toml file must explicitly declare its dependencies. To use a dependency
# from this list, specify "foo.workspace = true". For example:
#
#     [dependencies]
#     log.workspace = true
#
# See: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table
#
[workspace.dependencies]
anyhow = "1.0"
bincode = "1.3"
cc = "1.2"
hmac = "0.12"
sha2 = "0.10"
# We're disabling the default features for clap because we don't need the
# "suggestions" feature. That provides really amazing suggestions for typos, but
# it unfortunately does not seem to support localization.
#
# To use clap at all, you do need the std feature enabled, so enable that.
#
# See: https://docs.rs/clap/latest/clap/_features/index.html
clap = { version = "4.4.7", default-features = false, features = ["std"] }
embed-manifest = "1.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
which = "6.0"
win_etw_provider = "0.1.8"
win_etw_macros = "0.1.8"
windows = "0.57"
windows-registry = "0.1"
windows-service = "0.6"
winres = "0.1"

# For more profile settings, and details on the ones below, see https://doc.rust-lang.org/cargo/reference/profiles.html#profile-settings
[profile.release]
# Enable full debug info for optimized builds.
debug = "full"
# Split debuginfo into its own file to reduce binary size.
split-debuginfo = "packed"
lto = true
panic = "abort"
