name: "Bug report 🐛"
description: Report errors or unexpected behavior
labels: [Issue-Bug, Needs-Triage]
body:
- type: markdown
  attributes:
    value: |
      Please make sure to [search for existing issues](https://github.com/microsoft/sudo/issues) and [check the FAQ](https://github.com/microsoft/sudo/wiki/Frequently-Asked-Questions-(FAQ)) before filing a new one!
      If this is an application crash, please also provide a [Feedback Hub](https://aka.ms/sudo-feedback-hub) submission link so we can find your diagnostic data on the backend. Use the category "Apps > Windows Terminal" and choose "Share My Feedback" after submission to get the link.

- type: input
  attributes:
    label: Sudo for Windows version
    placeholder: "1.0.0"
    description: |
      You can find this with `sudo.exe --version` on the command line.
  validations:
    required: true

- type: input
  attributes:
    label: Windows build number
    placeholder: "10.0.26052.0"
    description: |
      Please run `ver` or `[Environment]::OSVersion`. Alternatively, the following command in PowerShell:
      Write-Host "Windows build: $((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").BuildLabEx)"
  validations:
    required: true

- type: textarea
  attributes:
    label: Other Software
    description: If you're reporting a bug about our interaction with other software, what software? What versions?
    placeholder: |
      vim 8.2 (inside WSL)
      OpenSSH_for_Windows_8.1p1
      My Cool Application v0.3 (include a code snippet if it would help!)
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps to reproduce
    placeholder: Tell us the steps required to trigger your bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: If you want to include screenshots, paste them into the markdown editor below.
    placeholder: What were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: Actual Behavior
    placeholder: What happened instead?
  validations:
    required: true
